version: '3'

services:

  bot:
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"
