version: '3'

services:

  bot:
    build: .
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      VAULT_ADDR: http://vault:8200
      VAULT_TOKEN: ${VAULT_TOKEN}
    depends_on:
      - redis
      - vault

  redis:
    image: redis:alpine
    command: redis-server --appendonly yes
    restart: always
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - "./redis-data:/data"

  vault:
    image: vault
    cap_add:
      - IPC_LOCK
    ports:
      - "8200:8200"
    volumes:
      - ./vault/file:/vault/file
      # - ./vault/config:/vault/config
