name: tests

on:
  pull_request:

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14

    - name: Test
      run: go test -v ./... -coverprofile out.prof
    - name: Coverage
      run: go tool cover -func ./out.prof
